<?php


/**
 * Implementation of hook_install().
 */
function states_install() {
  db_query("DELETE FROM {cache};");
}

/**
 * Implementation of hook_uninstall().
 */
function states_uninstall() {
  $states = preg_split('/[\r\n]+/', variable_get('defined_states', ''), -1, PREG_SPLIT_NO_EMPTY);
  foreach ($states as $key => &$value) {
    variable_del('states_' . $key);
  }
  variable_del('defined_states');
}
